[package]
name = "stack"
version = "0.1.0"
authors = ["gattlin1 <gattlin1@live.missouristate.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
